---
- name: Create the icons folder  # noqa risky-file-permissions
  file:
    path: "{{ docker_dir }}/{{ container_name }}/tools/homer-icons"
    state: directory

- name: Copy the icons  # noqa risky-file-permissions
  copy:
    src: "files/icons/{{ item.path.split('/')[-1] }}.png"
    dest: "{{ docker_dir }}/{{ container_name }}/tools/homer-icons"
    owner: "{{ username }}"
    group: "{{ username }}"
  when: lookup('vars', 'enable_' + item.path.split('/')[-1]) | default(False) and lookup('vars', item.path.split('/')[-1])['dashboard_url'] is defined
  with_items: "{{ containers.files }}"

- name: Copy the logo  # noqa risky-file-permissions
  copy:
    src: "files/icons/logo.jpg"
    dest: "{{ docker_dir }}/{{ container_name }}/tools/homer-icons"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy the custom stylesheet  # noqa risky-file-permissions
  copy:
    src: "files/custom.css"
    dest: "{{ docker_dir }}/{{ container_name }}"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Generate the Homer config file  # noqa risky-file-permissions
  template:
    src: config.yaml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/config.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
