---
- name: Make sure ddclient is installed  # noqa package-latest
  apt:
    name: ddclient
    state: latest
    update_cache: true

- name: Install the configuration file  # noqa risky-file-permissions
  template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
  register: config

- name: Make sure the ddclient service is started & enabled
  service:
    name: ddclient
    state: started
    enabled: true

- name: Restart the ddclient service on config change
  service:
    name: ddclient
    state: restarted
  listen: config.changed
