---
- name: Make sure ddclient is installed
  apt:
    name: ddclient
    state: latest
    update_cache: true

- name: Install the configuration file  # noqa risky-file-permissions
  template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
  register: config
  notify: Restart the ddclient service on config change

- name: Make sure the ddclient service is started & enabled
  service:
    name: ddclient
    state: started
    enabled: true
