---
    
- name: Make sure the Vaultwarden container is created and running
  docker_container:
    name: 'bitwarden'
    image: "vaultwarden/server"
    pull: true
    state: 'started'
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    env:
      WEBSOCKET_ENABLED: "true"
      INVITATIONS_ALLOWED: "false"
      SIGNUPS_ALLOWED: "false"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/data"
    restart_policy: unless-stopped


- name: Add {{ container_name }} to the SWAG network (reverse-proxy)
  docker_network:
    name: swag_network
    connected:
      - bitwarden
    appends: yes
  when: enable_swag