---
- name: Make sure the MariaDB container is created and running
  docker_container:
    name: "nextcloud-mariadb"
    image: "mariadb:latest"
    pull: true
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed --innodb-read-only-compressed=OFF"
    state: 'started'
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.icon": "custom"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "MYSQL_ROOT_PASSWORD": "{{ nextcloud_mysql_root_password }}"
      "MYSQL_DATABASE": "{{ nextcloud_mysql_db }}"
      "MYSQL_USER": "{{ nextcloud_mysql_user }}"
      "MYSQL_PASSWORD": "{{ nextcloud_mysql_password }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/mariadb/mysql:/var/lib/mysql"
    restart_policy: unless-stopped

- name: Make sure Redis is created and running
  docker_container:
    name: "nextcloud-redis"
    image: "redis:alpine"
    pull: true
    state: 'started'
    restart_policy: unless-stopped

- name: Make sure the Nextcloud app is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/nextcloud:php8"
    pull: true
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ docker_dir }}/{{ container_name }}/data:/data"
    restart_policy: unless-stopped

- name: Schedule a Nextcloud library scan at midnight every day
  cron:
    name: Scan the Nextcloud library
    hour: "0"
    job: "docker exec -it photoprism /photoprism/bin/photoprism index"
