---
- name: Make sure the Flame container is created and running
  docker_container:
    name: 'flame'
    image: "pawelmalak/flame:latest"
    pull: true
    state: 'started'
    ports:
      - "5005:5005"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/app/data"
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: unless-stopped