---
- name: Make sure the Plex container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/plex"
    pull: yes
    network_mode: host
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    devices:
      - "/dev/dri:/dev/dri"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ mergerfs_root }}/Media/TV:/tv"
      - "{{ mergerfs_root }}/Media/Movies:/movies"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped