---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "remie/youtransfer:stable"
    pull: yes
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Uploads:/uploads"
    restart_policy: unless-stopped
  
- name: Schedule a cleanup for /opt/youtransfer
  cron:
    name: Cleanup /opt/youtransfer
    hour: "0"
    job: "docker exec {{ container_name }} rm -rf /opt/youtransfer/upload_*"

- name: Add {{ container_name }} to the SWAG network (reverse-proxy)
  docker_network:
    name: swag_network
    connected:
      - "{{ container_name }}"
    appends: yes
  when: enable_swag